# Generated by Django 5.2 on 2026-10-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
